### ISSUE TITLE
Implementação do Módulo Disciplina

### ISSUE THREAD

**Issue by allandvieira** [Marea-Turbo1343/GerenciadordeTestes2024#5]
O cadastro de **Disciplinas** consiste de:

- nome

O campo nome é obrigatório.

Não pode registrar uma disciplina com o mesmo nome.

A disciplina deve armazenar informações sobre as matérias que serão relacionadas à ela posteriormente.

Não deve ser possível excluir disciplinas com matérias e testes relacionados.

**Protótipo:**

![Image](https://github.com/Marea-Turbo1343/GerenciadordeTestes2024/assets/106538716/e403b510-1cd2-46d5-b3f3-b23aa55f4182)

**Comment by TGCulau** [comment]
Revesindo codigo geral e implementado validação da duplicidade de disciplina
